query getProducts(
    $after: String
    $slug: [String]
    $first: Int = 9999
    $orderby: ProductsOrderByEnum = NAME
) {
    products(
        first: $first
        after: $after
        where: {
            categoryIn: $slug
            visibility: VISIBLE
            minPrice: 0
            orderby: { field: $orderby, order: ASC }
            status: "publish"
        }
    ) {
        pageInfo {
            hasNextPage
            endCursor
        }
        nodes {
            name
            slug
            type
            databaseId
            id
            averageRating
            reviewCount
            ...Terms
            ...ProductCategories
            ...SimpleProduct
            ...VariableProduct
            ...ExternalProduct
        }
    }
}
