name: Deploy to GitHub Pages

on:
    repository_dispatch:
        types: [trigger-deploy]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  persist-credentials: true

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 23.4

            - name: Create .env file
              run: |
                  echo "GQL_HOST=${{ secrets.GQL_HOST }}" >> .env
                  echo "NUXT_PUBLIC_PRODUCTS_PER_PAGE=${{ secrets.NUXT_PUBLIC_PRODUCTS_PER_PAGE }}" >> .env
                  echo "NUXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ secrets.NUXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}" >> .env
                  echo "PRIMARY_COLOR=${{ secrets.PRIMARY_COLOR }}" >> .env
                  echo "NUXT_IMAGE_DOMAINS=${{ secrets.NUXT_IMAGE_DOMAINS }}" >> .env
                  echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" >> .env
                  echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env
                  echo "APP_HOST=${{ secrets.APP_HOST }}" >> .env
                  echo "SITE_KEY=${{ secrets.SITE_KEY }}" >> .env

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run generate
              env:
                  GQL_HOST: ${{ secrets.GQL_HOST }}
                  NUXT_PUBLIC_PRODUCTS_PER_PAGE: ${{ secrets.NUXT_PUBLIC_PRODUCTS_PER_PAGE }}
                  NUXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NUXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
                  PRIMARY_COLOR: ${{ secrets.PRIMARY_COLOR }}
                  NUXT_IMAGE_DOMAINS: ${{ secrets.NUXT_IMAGE_DOMAINS }}
                  API_BASE_URL: ${{ secrets.API_BASE_URL }}
                  SITE_URL: ${{ secrets.SITE_URL }}
                  APP_HOST: ${{ secrets.APP_HOST }}
                  SITE_KEY: ${{ secrets.SITE_KEY }}

            - name: Configure Git
              run: |
                  git config --global user.name "jdbernardo16"
                  git config --global user.email "jdbernardo16@gmail.com"
                  git config --global url.https://${{ secrets.SECRET_TOKEN }}@github.com/.insteadOf https://github.com/

            - name: Deploy to GitHub Pages
              run: npm run deploy
